# Generated by Django 3.2.6 on 2021-08-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
                ('expiry_month', models.CharField(max_length=2)),
                ('expiry_year', models.CharField(max_length=2)),
                ('card_number', models.CharField(max_length=16)),
                ('owners_first_name', models.CharField(max_length=250)),
                ('owners_last_name', models.CharField(max_length=250)),
                ('ccv_code', models.CharField(max_length=3)),
            ],
        ),
    ]
