# Generated by Django 3.2.6 on 2021-08-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detail_description', models.TextField(blank=True, null=True)),
                ('availability', models.PositiveIntegerField(null=True)),
                ('accession_number', models.CharField(max_length=50)),
                ('product_condition', models.CharField(max_length=50)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('categories', models.ManyToManyField(related_name='product_category', to='product.Category')),
            ],
        ),
    ]
