# Generated by Django 3.2.6 on 2021-12-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Zniżka', 'verbose_name_plural': 'Zniżki'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_name',), 'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'Sezon', 'verbose_name_plural': 'Sezony'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tagi'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='whole_price_whole',
            new_name='whole_price_net',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='product_pictures'),
        ),
    ]
