# Generated by Django 3.2.6 on 2021-12-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211212_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_availability',
            field=models.PositiveIntegerField(default=0, verbose_name='Stan magazynowy'),
        ),
    ]
