# Generated by Django 3.2.6 on 2021-08-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210812_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(default='default.png', upload_to='product_pictures'),
        ),
    ]
