# Generated by Django 3.2.6 on 2021-12-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_stock_availability'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='cart.CartItem', to='product.Product', verbose_name='Produkty w koszyku'),
        ),
    ]
