# Generated by Django 3.2.6 on 2022-01-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='uuid',
            new_name='order_number',
        ),
    ]
